[package]
name = "mdblog"
version = "0.1.0"
authors = ["FuGangqiang <fu_gangqiang@qq.com>"]
description = "create blog from markdown files."
repository = "https://github.com/FuGangqiang/mdblog.rs"
keywords = ["blog", "markdown", "static", "site", "generator"]
license = "MIT"
readme = "README.md"

[dependencies]
getopts = "0.2"
walkdir = "0.1"
log = "0.3"
env_logger = "0.3"
tera = { git = "https://github.com/Keats/tera", rev = "31c092d40f0eeb932171c2d8031adfe6e0d45c3e" }
pulldown-cmark = "0.0.8"
serde_json = "0.8"
