[package]
name = "mdblog"
version = "0.12.1"
authors = ["FuGangqiang <fu_gangqiang@qq.com>"]
description = "static site generator from markdown files."
repository = "https://github.com/FuGangqiang/mdblog.rs"
homepage = "https://github.com/FuGangqiang/mdblog.rs"
documentation = "https://docs.rs/mdblog"
keywords = ["blog", "markdown", "static", "site", "generator"]
categories = ["command-line-utilities"]
license = "MIT"
readme = "README.md"

[[bin]]
name = "mdblog"
doc = false

[dependencies]
env_logger = "0.5"
structopt = "0.2"
log = "0.4"
pulldown-cmark = "0.1"
serde = { version = "1.0", features = ["rc", "std"] }
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.7"
toml = "0.4"
tera = "0.11"
walkdir = "2.1"
tempfile = "3"
config = "0.8"
failure = "0.1.1"
hyper = "0.11"
futures = "0.1"
open = "1.2"
notify = "4.0"
glob = "0.2"
percent-encoding = "1.0"
mime_guess = "2.0.0-alpha"
shellexpand = "1.0"
chrono = { version = "0.4", features = ["serde"] }
