[package]
name = "mdblog"
version = "0.1.7"
authors = ["FuGangqiang <fu_gangqiang@qq.com>"]
description = "create blog from markdown files."
repository = "https://github.com/FuGangqiang/mdblog.rs"
homepage = "https://github.com/FuGangqiang/mdblog.rs"
documentation = "http://fugangqiang.github.io/docs/mdblog.rs/mdblog/"
keywords = ["blog", "markdown", "static", "site", "generator"]
license = "MIT"
readme = "README.md"

[[bin]]
name = "mdblog"
doc = false

[dependencies]
getopts = "0.2"
walkdir = "0.1"
log = "0.3"
env_logger = "0.3"
tera = "0.1.3"
pulldown-cmark = "0.0.8"
serde_json = "0.8"
chrono = "0.2"
toml = "0.2"
