[package]
name = "mdblog"
version = "0.2.0"
authors = ["FuGangqiang <fu_gangqiang@qq.com>"]
description = "create static site blog from markdown files."
repository = "https://github.com/FuGangqiang/mdblog.rs"
homepage = "https://github.com/FuGangqiang/mdblog.rs"
documentation = "https://docs.rs/mdblog"
keywords = ["blog", "markdown", "static", "site", "generator"]
categories = ["command-line-utilities"]
license = "MIT"
readme = "README.md"

[[bin]]
name = "mdblog"
doc = false

[dependencies]
chrono = "0.4"
env_logger = "0.5"
getopts = "0.2"
log = "0.4"
pulldown-cmark = "0.1"
serde_json = "1.0"
tera = "0.11"
walkdir = "2.1"
config = "0.8"
failure = "0.1.1"
