[package]
name = "mdblog"
version = "0.1.8"
authors = ["FuGangqiang <fu_gangqiang@qq.com>"]
description = "create static site blog from markdown files."
repository = "https://github.com/FuGangqiang/mdblog.rs"
homepage = "https://github.com/FuGangqiang/mdblog.rs"
documentation = "https://docs.rs/mdblog"
keywords = ["blog", "markdown", "static", "site", "generator"]
categories = ["Command line utilities"]
license = "MIT"
readme = "README.md"

[[bin]]
name = "mdblog"
doc = false

[dependencies]
getopts = "0.2"
walkdir = "1.0"
log = "0.3"
env_logger = "0.4"
tera = "0.10"
pulldown-cmark = "0.0.14"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = "0.3"
toml = "0.4"
