[package]
name = "mdblog"
version = "0.0.1"
authors = ["FuGangqiang <fu_gangqiang@qq.com>"]
description = "create blog from markdown files."
repository = "https://github.com/FuGangqiang/mdblog.rs"
keywords = ["blog", "markdown", "mdblog"]
license = "MIT"
readme = "README.md"

[dependencies]
