
chain_indent = "Visual"
chain_split_single_child = false
chain_one_line_max = 60
closure_block_indent_threshold = 1
wrap_comments = true
comment_width = 120
fn_args_density = "Compressed"
fn_args_paren_newline = false
fn_brace_style = "SameLineWhere"
fn_return_indent = "WithWhereClause"
force_format_strings = false
hard_tabs = false
indent_match_arms = true
item_brace_style = "SameLineWhere"
max_width = 120
match_block_trailing_comma = true
newline_style = "Unix"
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
struct_lit_multiline_style = "ForceMulti"
struct_lit_style = "Block"
tab_spaces = 4
take_source_hints = true
trailing_comma = "Vertical"
type_punctuation_density = "Compressed"
use_try_shorthand = true
where_density = "Vertical"
where_layout = "Vertical"
where_pred_indent = "Visual"
where_style = "Default"
wrap_match_arms = true
write_mode = "Overwrite"
