theme = "simple"
site_name = "Mdblog"
site_motto = "Simple is Beautiful!"
footer_note = "Keep It Simple, Stupid!"
media_dir = "media"
build_dir = "_build"
theme_root_dir = "_themes"
rebuild_interval = 2
url_prefix = "/mdblog.rs"
